name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: yarn install
      
      - name: Build
        env:
          REACT_APP_EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
          REACT_APP_SERVICE_ID: ${{ secrets.SERVICE_ID }}
          REACT_APP_TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          REACT_APP_TURNSTILE_SITE_KEY: ${{ secrets.TURNSTILE_SITE_KEY }}
        run: yarn build
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build